import loadable from '@loadable/component';
import { UnderConstructionandDevelopmentComponent } from '../../../Components';
const ContactsModule = loadable(() => import('../../../Views/Home/Contacts/Contacts.Module'));
const CorporateModule = loadable(() => import('../../../Views/Home/Corporate/Corporate.Module'));
const SettingsModule = loadable(() => import('../../../Views/Home/Settings/Settings.Module'));
export const HomeRoutes = [
  {
    id: 1,
    path: '/contacts',
    name: 'Shared:contacts',
    component: ContactsModule,
    layout: '/home',
    default: true,
    isRoute: true,
    authorize: true,
    isDisabled: false,
    isExact: false,
  },
  {
    id: 2,
    path: '/corporate',
    name: 'Shared:corporate',
    component: CorporateModule,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    isDisabled: false,
    isExact: false,
  },
  {
    id: 3,
    path: '/projects',
    name: 'Shared:projects',
    component: UnderConstructionandDevelopmentComponent,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    isDisabled: false,
    isExact: false,
  },
  {
    id: 4,
    path: '/dashboard',
    name: 'Shared:projects',
    component: UnderConstructionandDevelopmentComponent,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    isDisabled: false,
    isExact: false,
  },{
    id: 5,
    path: '/settings',
    name: 'Shared:Settings',
    component: SettingsModule,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    isDisabled: false,
    isExact: false,
  },
];
