export const ProductionServiceMenu = [
  {
    path: '/home/corporate/company/Production',
    name: 'Shared:Production',
    icon: 'mdi mdi-camera-gopro',
    order: 1,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Wardrobe',
    name: 'Shared:Wardrobe',
    icon: 'mdi mdi-wardrobe',
    order: 2,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Locations',
    name: 'Shared:Locations',
    icon: 'mdi mdi-map-marker-multiple-outline',
    order: 3,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Talent-Casting',
    name: 'Shared:Talent-Casting',
    icon: 'mdi mdi-cast-audio',
    order: 4,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Art',
    name: 'Shared:Art',
    icon: 'mdi mdi-palette',
    order: 5,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Props',
    name: 'Shared:Props',
    icon: 'mdi mdi-propane-tank-outline',
    order: 6,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Transportation',
    name: 'Shared:Transportation',
    icon: 'mdi mdi-train-car',
    order: 7,
    isLastChildrenInMainMenu: false,
    childrens: [],
  },
  {
    path: '/home/corporate/company/Catering',
    name: 'Shared:Catering',
    icon: 'mdi mdi-certificate',
    order: 8,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
];
