import {
  CoursesView,
  DepartmentView,
  LeavePolicyView,
  RefferralView,
  RequestView,
  ShiftView,
  TeamView,
} from '../../../../../Views';

export const ContactsModuleRoutes = [
  {
    path: '/department',
    name: 'DepartmentView:employees',
    component: DepartmentView,
    layout: '/home/users',
    default: true,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/courses',
    name: 'CoursesView:courses',
    component: CoursesView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/leave-policy',
    name: 'LeavePolicyView:leave-policy',
    component: LeavePolicyView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/refferral',
    name: 'RefferralView:refferral',
    component: RefferralView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/request',
    name: 'RequestView:request',
    component: RequestView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/shift',
    name: 'ShiftView:shift',
    component: ShiftView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
  {
    path: '/team',
    name: 'TeamView:team',
    component: TeamView,
    layout: '/home/users',
    default: false,
    isRoute: true,
    authorize: true,
    isExact: false,
  },
];
