export const HumanResourcesMenu = [
  {
    path: '/home/corporate/company/human-resources/test',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-account-tie',
    order: 1,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/2',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-account-group',
    order: 2,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Attendance',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-domain',
    order: 3,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/4',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-license',
    order: 4,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/5',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-human-capacity-increase',
    order: 5,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/6',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-mdi mdi-finance',
    order: 6,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/7',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-account-search',
    order: 7,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/8',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-account-convert',
    order: 8,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/9',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-mdi mdi-scale-balance',
    order: 9,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/all-Screen-Systems',
    name: 'Shared:human-resources',
    icon: 'mdi mdi-mdi mdi-desktop-mac-dashboard c-blue-dark',
    order: 10,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
];
