export const HumanResourcesMenu = [
  {
    path: '/home/corporate/company/human-resources/employee',
    name: 'Shared:Company-Employees',
    icon: 'mdi mdi-account-tie',
    order: 1,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/leave',
    name: 'Shared:TimeOFFLeave',
    icon: 'mdi mdi-account-group',
    order: 2,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Attendance',
    name: 'Shared:Attendancescheckinout',
    icon: 'mdi mdi-domain',
    order: 3,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/shift',
    name: 'Shared:ShiftScheduler',
    icon: 'mdi mdi-license',
    order: 4,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Recruitment',
    name: 'Shared:Recruitment',
    icon: 'mdi mdi-human-capacity-increase',
    order: 5,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Refferral',
    name: 'Shared:Refferral',
    icon: 'mdi mdi-mdi mdi-finance',
    order: 6,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Performance-Appraisal',
    name: 'Shared:PerformanceAppraisal',
    icon: 'mdi mdi-account-search',
    order: 7,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/E-Learning',
    name: 'Shared:E-Learning',
    icon: 'mdi mdi-account-convert',
    order: 8,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/Termination-Profile',
    name: 'Shared:Termination-Profile',
    icon: 'mdi mdi-mdi mdi-scale-balance',
    order: 9,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },

  {
    path: '/home/corporate/company/human-resources/Requests-Approvals',
    name: 'Shared:Requests-Approvals',
    icon: 'mdi mdi-content-save-off-outline c-blue-dark',
    order: 10,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
  {
    path: '/home/corporate/company/human-resources/all-Screen-Systems',
    name: 'Shared:All Screen Systems',
    icon: 'mdi mdi-mdi mdi-desktop-mac-dashboard c-blue-dark',
    order: 11,
    isExact: true,
    isLastChildrenInMainMenu: true,
    childrens: [],
  },
];
